### PR TITLE
Added account page content, updated links in navbar for new default page

### PR DESCRIPTION
**Pull request by salsajeries**
Should be approved before making the path change, to make sure the new path is implemented everywhere necessary

### CODE REVIEW

**Comment by salsajeries** [comment]
@drewbotts @ChainReaction31 if there are no issues with this change, I'll go ahead and finish the merge tomorrow!

**Review by ChainReaction31 — DISMISSED** [review]
I think this will merge cleanly. It will need a rebase which will look kind of scary when you see the commit but it's just the history catching up.

**Review by ChainReaction31 — APPROVED** [review]
I rebased the branch which collected the history of nightly so far while keeping @salsajeries changes. I did not see any issues in the app running aside from a few things that aren't related to this.

**Comment by ChainReaction31** [comment]
This is a good start, but it does need to modify the current user and should probably redirect to the dashboard which are both easy enough to implement.

**Review by drewbotts — APPROVED** [review]

**Comment by ChainReaction31** [comment]
Alright this will allow the merge to proceed. I'll test it here after closing this and making a few updates

**Pull request merged**
